global using asfalis.Shared.DTOs;
global using asfalis.Shared.Models;
global using asfalis.Shared.Services;
global using System.Net.Http.Json;
global using System.Text.Json;
global using Blazored.LocalStorage;
global using asfalis.Client.Services;
global using asfalis.Client.AuthStates;
global using Microsoft.AspNetCore.Components.Authorization;
